### ISSUE TITLE
Failed to load the run-in-terminal package

### ISSUE THREAD

**Issue by ghost** [pohmelie/run-in-terminal#22]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.32.0-dev-7865464 x64
**Electron**: 2.0.7
**OS**: Microsoft Windows 10 Pro N
**Thrown From**: [run-in-terminal](https://github.com/pohmelie/run-in-terminal) package 1.0.1

### Stack Trace

Failed to load the run-in-terminal package

```
At Syntax error on line 1, column 1: Unexpected t

SyntaxError: Syntax error on line 1, column 1: Unexpected t
    at e (~/AppData/Local/Atom Dev x64/app-dev/resources/app/static/<embedded>:14:1775989)
    at Object.t.exports [as parse] (~/AppData/Local/Atom Dev x64/app-dev/resources/app/static/<embedded>:14:1776043)
    at m (~/AppData/Local/Atom Dev x64/app-dev/resources/app/static/<embedded>:11:564117)
    at c (~/AppData/Local/Atom Dev x64/app-dev/resources/app/static/<embedded>:11:564323)
    at Object.readFileSync (~/AppData/Local/Atom Dev x64/app-dev/resources/app/static/<embedded>:11:565402)
    at keymaps.getKeymapPaths.map.e (~/AppData/Local/Atom Dev x64/app-dev/resources/app/static/<embedded>:11:3001644)
    at Array.map (<anonymous>)
    at Package.loadKeymaps (~/AppData/Local/Atom Dev x64/app-dev/resources/app/static/<embedded>:11:3001632)
    at measure (~/AppData/Local/Atom Dev x64/app-dev/resources/app/static/<embedded>:11:2995193)
    at Package.measure (~/AppData/Local/Atom Dev x64/app-dev/resources/app/static/<embedded>:11:2994395)
    at Package.load (~/AppData/Local/Atom Dev x64/app-dev/resources/app/static/<embedded>:11:2995129)
    at PackageManager.loadAvailablePackage (~/AppData/Local/Atom Dev x64/app-dev/resources/app/static/<embedded>:11:368986)
    at PackageManager.loadPackage (~/AppData/Local/Atom Dev x64/app-dev/resources/app/static/<embedded>:11:367714)
    at PackageManager.activatePackage (~/AppData/Local/Atom Dev x64/app-dev/resources/app/static/<embedded>:11:370218)
    at ~/AppData/Local/Atom Dev x64/app-dev/resources/app/static/<embedded>:11:887497
    at r (~/AppData/Local/Atom Dev x64/app-dev/resources/app/static/<embedded>:11:882347)
    at o (~/AppData/Local/Atom Dev x64/app-dev/resources/app/static/<embedded>:14:1023308)
    at ChildProcess.n.process.on.e (~/AppData/Local/Atom Dev x64/app-dev/resources/app/static/<embedded>:14:1023514)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```

### Commands

```
```

### Non-Core Packages

```
generate-word-count 0.0.0 
platformio-ide-terminal 2.8.4 
run-in-terminal 1.0.1 
```

**Comment by pohmelie** [comment]
More info? I can't say what is going wrong by this stacktrace.

**Comment by ghost** [comment]
I am trying to install run in terminal by installing the package by default install option in atom.  While Installing the package I facing this issue..

OS : Windows
Atom : 1.32.0-dev-7865464

**Comment by pohmelie** [comment]
It looks like you try dev version. Package installs and runs fine on atom 1.30.0, which is latest stable release.
